version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./docker-test-client
    ports:
      - "3000:3000"

  server:
    container_name: server
    build:
      context: ./docker-test-server
    ports:
      - "4000:4000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
